auto_accept: True
file_roots:
  base:
    - /srv/tsplk-formula/salt
    - /srv/salty-splunk/file_base
    - /srv/salty-splunk/formulas/nfs

pillar_roots:
  base:
    - /srv/pillar
    - /srv/.credential

runner_dirs:
  - /srv/salty-splunk/file_base/runners
peer_run:
  .*:
    - splunk.*

timeout: 60
fileserver_backend:
  - roots
  - s3fs

s3.buckets:
  base:
    - tsplk-{{ user }}

# not working right now,
# see https://github.com/saltstack/salt/issues/31664
#ext_pillar:
#  - s3:
#    bucket: tsplk-bucket
#    prefix: base/{{ user }}/{{ project }}/pillar