auto_accept: True
file_roots:
  base:
    - /srv/tsplk-formula/salt
    - /srv/salty-splunk/file_base
    - /srv/salty-splunk/formulas/nfs
    - /srv/tsplk-formula/reactor

pillar_roots:
  base:
    - /srv/pillar
    - /srv/.credential

runner_dirs:
  - /srv/salty-splunk/file_base/runners
peer_run:
  .*:
    - splunk.*

timeout: 60
fileserver_backend:
  - roots

reactor:
  - 'salt/minion/*/start':
    - /srv/tsplk-formula/reactor/start.sls

# for s3 sync data able to work, need to provide the region
# refer to https://github.com/saltstack/salt/issues/28913
s3.location: us-west-2
#reactor:                            # Master config section "reactor"
#  - 'salt/minion/*/start':          # Match tag "salt/minion/*/start"
#    - salt://reactor/minion-start.sls        # Things to do when a minion starts
##    - /srv/reactor/monitor.sls      # Other things to do

# not useful now since it will sync all files in the bucket
#s3.buckets:
#  base:
#    - tsplk-{{ user }}

# not working right now,
# see https://github.com/saltstack/salt/issues/31664
#ext_pillar:
#  - s3:
#    bucket: tsplk-bucket
#    prefix: base/{{ user }}/{{ project }}/pillar