auto_accept: True
file_roots:
  base:
    - /srv/salty-splunk/file_base
    - /srv/salty-splunk/formulas/nfs

pillar_roots:
  base:
    - /srv/salt/pillar
runner_dirs:
  - /srv/salty-splunk/file_base/runners
peer_run:
  .*:
    - splunk.*

timeout: 60
fileserver_backend:
  - roots